-- Run this in Supabase SQL Editor to update your products
DELETE FROM public.plans;
DELETE FROM public.products;

INSERT INTO public.products (id, name, description, features, image) VALUES
('drip-client-non-root', 'Drip Client NON ROOT', 'Premium Drip Client NON ROOT tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('drip-client-proxy', 'Drip Client PROXY', 'Premium Drip Client PROXY tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('hg-cheats-non-root', 'HG CHEATS Non ROOT', 'Premium HG CHEATS Non ROOT tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('hg-apk-proxy', 'HG APK PROXY', 'Premium HG APK PROXY tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('prime-hook-non-root', 'Prime Hook Non root', 'Premium Prime Hook Non root tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('patoteam-non-root', 'PatoTeam NON ROOT', 'Premium PatoTeam NON ROOT tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('ghost-elite-steemer-root', 'GHOST ELITE STEEMER ROOT', 'Premium GHOST ELITE STEEMER ROOT tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('br-mod-root', 'BR MOD  ROOT', 'Premium BR MOD  ROOT tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('hikari-mod-root', 'HIKARI MOD ROOT', 'Premium HIKARI MOD ROOT tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('xyz-cheats-safe-root', 'XYZ CHEATS SAFE ROOT', 'Premium XYZ CHEATS SAFE ROOT tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('hex-blade-ff-root', 'HEX BLADE FF Root', 'Premium HEX BLADE FF Root tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('neo-strike-root', 'NEO STRIKE Root', 'Premium NEO STRIKE Root tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('haxx-cker-pro-root', 'HAXX-CKER PRO Root', 'Premium HAXX-CKER PRO Root tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('reaper-x-pro-root', 'Reaper x Pro Root', 'Premium Reaper x Pro Root tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('drip-clint-pc-aim-kill', 'DRIP CLINT PC AIM KILL', 'Premium DRIP CLINT PC AIM KILL tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('br-mod-pc-aim-kill', 'BR MOD PC AIM KILL', 'Premium BR MOD PC AIM KILL tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('esgin-gbox-certificate-ios', 'Esgin Gbox Certificate iOs', 'Premium Esgin Gbox Certificate iOs tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('ios-fluorite', 'ios Fluorite', 'Premium ios Fluorite tool with the best features.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('migul-iphone-ios-basic', 'MIGUL iPhone ios Basic', 'Premium bypass and mod for iOS.', '["Auto Aim", "ESP", "Anti-Ban"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop'),
('migul-iphone-ios-pro', 'MIGUL iPhone ios Pro', 'Ultimate bypass and mod for iOS.', '["Auto Aim", "ESP", "Anti-Ban", "No Recoil"]', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop');

INSERT INTO public.plans (id, product_id, duration, price) VALUES
('plan-drip-client-non-root-1-days', 'drip-client-non-root', '1 Days', 80.00),
('plan-drip-client-non-root-3-days', 'drip-client-non-root', '3 Days', 190.00),
('plan-drip-client-non-root-7-days', 'drip-client-non-root', '7 Days', 350.00),
('plan-drip-client-non-root-15-days', 'drip-client-non-root', '15 Days', 630.00),
('plan-drip-client-non-root-30-days', 'drip-client-non-root', '30 Days', 900.00),
('plan-drip-client-proxy-1-days', 'drip-client-proxy', '1 Days', 80.00),
('plan-drip-client-proxy-3-days', 'drip-client-proxy', '3 Days', 190.00),
('plan-drip-client-proxy-7-days', 'drip-client-proxy', '7 Days', 350.00),
('plan-drip-client-proxy-15-days', 'drip-client-proxy', '15 Days', 630.00),
('plan-drip-client-proxy-30-days', 'drip-client-proxy', '30 Days', 900.00),
('plan-hg-cheats-non-root-1-days', 'hg-cheats-non-root', '1 Days', 90.00),
('plan-hg-cheats-non-root-7-days', 'hg-cheats-non-root', '7 Days', 350.00),
('plan-hg-cheats-non-root-10-days', 'hg-cheats-non-root', '10 Days', 400.00),
('plan-hg-cheats-non-root-30-days', 'hg-cheats-non-root', '30 Days', 830.00),
('plan-hg-apk-proxy-1-days', 'hg-apk-proxy', '1 Days', 90.00),
('plan-hg-apk-proxy-7-days', 'hg-apk-proxy', '7 Days', 350.00),
('plan-hg-apk-proxy-10-days', 'hg-apk-proxy', '10 Days', 400.00),
('plan-hg-apk-proxy-30-days', 'hg-apk-proxy', '30 Days', 830.00),
('plan-prime-hook-non-root-1-days', 'prime-hook-non-root', '1 Days', 80.00),
('plan-prime-hook-non-root-3-days', 'prime-hook-non-root', '3 Days', 149.40),
('plan-prime-hook-non-root-7-days', 'prime-hook-non-root', '7 Days', 319.50),
('plan-prime-hook-non-root-10-days', 'prime-hook-non-root', '10 Days', 349.20),
('plan-patoteam-non-root-1-day', 'patoteam-non-root', '1 Day', 150.00),
('plan-patoteam-non-root-3-days', 'patoteam-non-root', '3 Days', 220.00),
('plan-patoteam-non-root-7-days', 'patoteam-non-root', '7 Days', 360.00),
('plan-patoteam-non-root-15-days', 'patoteam-non-root', '15 Days', 620.00),
('plan-patoteam-non-root-30-days', 'patoteam-non-root', '30 Days', 1030.00),
('plan-ghost-elite-steemer-root-1-days', 'ghost-elite-steemer-root', '1 Days', 90.00),
('plan-ghost-elite-steemer-root-10-days', 'ghost-elite-steemer-root', '10 Days', 400.00),
('plan-ghost-elite-steemer-root-20-days', 'ghost-elite-steemer-root', '20 Days', 750.00),
('plan-ghost-elite-steemer-root-30-days', 'ghost-elite-steemer-root', '30 Days', 999.00),
('plan-br-mod-root-1-days', 'br-mod-root', '1 Days', 80.00),
('plan-br-mod-root-7-days', 'br-mod-root', '7 Days', 350.00),
('plan-br-mod-root-15-days', 'br-mod-root', '15 Days', 650.00),
('plan-br-mod-root-30-days', 'br-mod-root', '30 Days', 999.00),
('plan-hikari-mod-root-3-days', 'hikari-mod-root', '3 Days', 150.00),
('plan-hikari-mod-root-7-days', 'hikari-mod-root', '7 Days', 300.00),
('plan-hikari-mod-root-15-days', 'hikari-mod-root', '15 Days', 650.00),
('plan-hikari-mod-root-30-days', 'hikari-mod-root', '30 Days', 1100.00),
('plan-xyz-cheats-safe-root-1-days', 'xyz-cheats-safe-root', '1 Days', 150.00),
('plan-xyz-cheats-safe-root-7-days', 'xyz-cheats-safe-root', '7 Days', 350.00),
('plan-xyz-cheats-safe-root-15-days', 'xyz-cheats-safe-root', '15 Days', 650.00),
('plan-xyz-cheats-safe-root-30-days', 'xyz-cheats-safe-root', '30 Days', 999.00),
('plan-hex-blade-ff-root-1-days', 'hex-blade-ff-root', '1 Days', 80.00),
('plan-hex-blade-ff-root-7-days', 'hex-blade-ff-root', '7 Days', 300.00),
('plan-hex-blade-ff-root-15-days', 'hex-blade-ff-root', '15 Days', 550.00),
('plan-hex-blade-ff-root-30-days', 'hex-blade-ff-root', '30 Days', 999.00),
('plan-neo-strike-root-1-days', 'neo-strike-root', '1 Days', 80.00),
('plan-neo-strike-root-3-days', 'neo-strike-root', '3 Days', 150.00),
('plan-neo-strike-root-7-days', 'neo-strike-root', '7 Days', 300.00),
('plan-neo-strike-root-14-days', 'neo-strike-root', '14 Days', 550.00),
('plan-haxx-cker-pro-root-10-days', 'haxx-cker-pro-root', '10 Days', 550.00),
('plan-haxx-cker-pro-root-20-days', 'haxx-cker-pro-root', '20 Days', 1100.00),
('plan-haxx-cker-pro-root-30-days', 'haxx-cker-pro-root', '30 Days', 1800.00),
('plan-reaper-x-pro-root-10-days', 'reaper-x-pro-root', '10 Days', 350.00),
('plan-drip-clint-pc-aim-kill-1-days', 'drip-clint-pc-aim-kill', '1 Days', 150.00),
('plan-drip-clint-pc-aim-kill-7-days', 'drip-clint-pc-aim-kill', '7 Days', 450.00),
('plan-drip-clint-pc-aim-kill-15-days', 'drip-clint-pc-aim-kill', '15 Days', 860.00),
('plan-drip-clint-pc-aim-kill-30-days', 'drip-clint-pc-aim-kill', '30 Days', 1150.00),
('plan-br-mod-pc-aim-kill-1-days', 'br-mod-pc-aim-kill', '1 Days', 120.00),
('plan-br-mod-pc-aim-kill-10-days', 'br-mod-pc-aim-kill', '10 Days', 550.00),
('plan-br-mod-pc-aim-kill-30-days', 'br-mod-pc-aim-kill', '30 Days', 1050.00),
('plan-esgin-gbox-certificate-ios-30-days-validity', 'esgin-gbox-certificate-ios', '30 Days Validity', 550.00),
('plan-ios-fluorite-1-days', 'ios-fluorite', '1 Days', 400.00),
('plan-ios-fluorite-7-days', 'ios-fluorite', '7 Days', 1349.00),
('plan-ios-fluorite-30-days', 'ios-fluorite', '30 Days', 2249.00),
('plan-migul-basic-1-days', 'migul-iphone-ios-basic', '1 Days', 300.00),
('plan-migul-basic-7-days', 'migul-iphone-ios-basic', '7 Days', 600.00),
('plan-migul-basic-30-days', 'migul-iphone-ios-basic', '30 Days', 1500.00),
('plan-migul-pro-1-days', 'migul-iphone-ios-pro', '1 Days', 400.00),
('plan-migul-pro-7-days', 'migul-iphone-ios-pro', '7 Days', 1000.00),
('plan-migul-pro-30-days', 'migul-iphone-ios-pro', '30 Days', 2250.00);
